kind/docs:
  - docs/**/*

kind/ui:
  - web_src/**/*
  - all: ["templates/**/*", "!templates/swagger/v1_json.tmpl"]

kind/api:
  - templates/swagger/v1_json.tmpl

kind/build:
  - Makefile
  - Dockerfile
  - Dockerfile.rootless
  - webpack.config.js

kind/lint:
  - .eslintrc.yaml
  - .golangci.yml
  - .markdownlint.yaml
  - .spectral.yaml
  - .stylelintrc.yaml
