root = "."
tmp_dir = ".air"

[build]
cmd = "make --no-print-directory backend"
bin = "gitea"
delay = 1000
include_ext = ["go", "tmpl"]
include_file = ["main.go"]
include_dir = ["internal/cmd", "internal/models", "internal/modules", "options", "internal/routers", "internal/services"]
exclude_dir = ["internal/modules/git/tests", "internal/services/gitdiff/testdata", "internal/modules/avatar/testdata", "internal/models/fixtures", "internal/models/migrations/fixtures", "internal/modules/migration/file_format_testdata", "internal/modules/avatar/identicon/testdata"]
exclude_regex = ["_test.go$", "_gen.go$"]
stop_on_error = true
