image: gitpod/workspace-full:latest

tasks:
  - name: Setup
    init: |
      make deps
      export GITEA__server__ROOT_URL="https://3000-$GITPOD_WORKSPACE_ID.${GITPOD_WORKSPACE_CLUSTER_HOST}/"
    command: |
      gp sync-done setup
      exit 0
  - name: Run frontend
    command: |
      gp sync-await setup
      make watch-frontend
  - name: Run backend
    command: |
      gp sync-await setup
      export TAGS="bindata sqlite sqlite_unlock_notify"
      make watch-backend

vscode:
  extensions:
    - editorconfig.editorconfig
    - dbaeumer.vscode-eslint
    - golang.go

ports:
  - name: Gitea
    port: 3000
