version: "2"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.rootless
    restart: always
    volumes:
      - ./data:/var/lib/gitea
      - ./config:/data/gitea/conf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"
