name: files changed

on:
  workflow_call:
    outputs:
      docs:
        description: "wehther docs files changed"
        value: ${{ jobs.files-changed.outputs.docs }}
      backend:
        description: "wehther backend files changed"
        value: ${{ jobs.files-changed.outputs.backend }}
      frontend:
        description: "wehther frontend files changed"
        value: ${{ jobs.files-changed.outputs.frontend }}

jobs:
  files-changed:
    name: detect what files changed
    runs-on: ubuntu-latest
    timeout-minutes: 3
    # Map a step output to a job output
    outputs:
      docs: ${{ steps.changes.outputs.docs }}
      backend: ${{ steps.changes.outputs.backend }}
      frontend: ${{ steps.changes.outputs.frontend }}
    steps:
      - uses: actions/checkout@v3
      - name: Check for backend file changes
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: .github/file-filters.yml
