name: files-changed

on:
  workflow_call:
    outputs:
      backend:
        value: ${{ jobs.detect.outputs.backend }}
      frontend:
        value: ${{ jobs.detect.outputs.frontend }}
      docs:
        value: ${{ jobs.detect.outputs.docs }}
      actions:
        value: ${{ jobs.detect.outputs.actions }}
      templates:
        value: ${{ jobs.detect.outputs.templates }}
      docker:
        value: ${{ jobs.detect.outputs.docker }}

jobs:
  detect:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    outputs:
      backend: ${{ steps.changes.outputs.backend }}
      frontend: ${{ steps.changes.outputs.frontend }}
      docs: ${{ steps.changes.outputs.docs }}
      actions: ${{ steps.changes.outputs.actions }}
      templates: ${{ steps.changes.outputs.templates }}
      docker: ${{ steps.changes.outputs.docker }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: changes_check
        if: env.ACT_EXEC != 'true'
        with:
          filters: |
            backend:
              - "**/*.go"
              - "templates/**/*.tmpl"
              - "go.mod"
              - "go.sum"
              - "Makefile"

            frontend:
              - "**/*.js"
              - "web_src/**"
              - "package.json"
              - "package-lock.json"
              - "Makefile"

            docs:
              - "**/*.md"
              - "docs/**"

            actions:
              - ".github/workflows/*"

            templates:
              - "templates/**/*.tmpl"
              - "poetry.lock"

            docker:
              - "Dockerfile"
              - "Dockerfile.rootless"
              - "docker/**"
              - "Makefile"
      - name: set outputs result
        id: changes
        run: |
          if [ "$ACT_EXEC" == 'true' ]; then
            # set default value for 'act_runner exec'
            { echo "backend=true" ; \
            echo "frontend=true" ; \
            echo "docs=true" ; \
            echo "actions=true" ; \
            echo "templates=true" ; \
            echo "docker=true" ; } >> "$GITHUB_OUTPUT"
          else
            { echo "backend=${{ steps.changes_check.outputs.backend }}" ; \
            echo "frontend=${{ steps.changes_check.outputs.frontend }}" ; \
            echo "docs=${{ steps.changes_check.outputs.docs }}" ; \
            echo "actions=${{ steps.changes_check.outputs.actions }}" ; \
            echo "actions=${{ steps.changes_check.outputs.templates }}" ; \
            echo "actions=${{ steps.changes_check.outputs.docker }}" ; } >> "$GITHUB_OUTPUT"
          fi
