name: compliance-docs

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  files-changed:
    name: detect what files changed
    runs-on: ubuntu-latest
    timeout-minutes: 3
    # Map a step output to a job output
    outputs:
      docs: ${{ steps.changes.outputs.docs }}
    steps:
      - uses: actions/checkout@v3  # v2
      - name: Check for backend file changes
        uses: dorny/paths-filter@v2  # v2
        id: changes
        with:
          filters: .github/file-filters.yml

  compliance-docs:
    if: needs.files-changed.outputs.docs == 'true'
    needs: files-changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: make deps-frontend
      - run: make lint-md
